feat:缩减store微服务的子模块数量 #9225
TencentBlueKing/bk-ci pull request #10035
Opened 2024-02-27 02:31 UTC by yjieliang

feat:缩减store微服务的子模块数量 #9225

2024-02-28 07:11 UTC, carlyin0801 commented on src/backend/ci/core/worker/worker-common/build.gradle.kts
> +    api(project(":core:misc:api-image"))
不要依赖这个模块，看就用了一个bean，建议在worker重新定义一个

2024-02-28 07:20 UTC, carlyin0801 commented on src/backend/ci/core/store/biz-store/build.gradle.kts
> +    api(project(":core:misc:api-image"))
不要依赖misc模块

2024-03-06 09:11 UTC, carlyin0801 approved these changes
1

2024-03-07 02:50 UTC, mingshewhe approved these changes

2024-03-07 03:28 UTC, irwinsun approved these changes

2024-03-07 03:31 UTC, irwinsun requested changes
boot-assembly 需要依赖 biz-store

2024-03-07 03:51 UTC, irwinsun approved these changes

2024-03-14 03:25 UTC, merged