feat：支持在父流水线中查看异步执行的子流水线的状态 #10260
TencentBlueKing/bk-ci pull request #10435
Opened 2024-05-29 07:59 UTC by hejieehe

#10260

2024-06-03 08:27 UTC, mingshewhe requested changes

2024-06-03 08:27 UTC, mingshewhe commented on src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/control/BuildStartControl.kt
> +        subPipelineStatusService.onAsyncStart(this)
应该接受status广播事件，不是直接调用

2024-06-03 08:27 UTC, mingshewhe commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStatusService.kt
> +        val keys = setOf(
只有异步执行才需要变更，不然不需要变更

2024-06-07 08:17 UTC, mingshewhe requested changes

2024-06-07 08:37 UTC, mingshewhe commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/utils/Constants.kt
> +const val PIPELINE_RUN_MODE = "BK_CI_SUB_PIPELINE_RUN_MODE"
变量名改成PIPELINE_START_SUB_RUN_MODE

2024-06-26 08:45 UTC, mingshewhe commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStatusService.kt
> +            logger.info("The build is not started asynchronously|$projectId|$pipelineId|$buildId")
这日志可以不输出

2024-06-26 08:50 UTC, mingshewhe commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStatusService.kt
> +                    asyncStatus = event.status
这个状态不对,需要使用getSubPipelineStatusFromDB(event.projectId, buildId)获取的状态

2024-06-26 10:18 UTC, mingshewhe approved these changes

2024-06-27 03:24 UTC, mingshewhe approved these changes

2024-07-04 12:48 UTC, mingshewhe commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> +        } else {
这个代码需要删除,启动时通过onBuildStart事件来处理了

2024-07-04 12:52 UTC, mingshewhe commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStatusService.kt
> +        pipelineRuntimeService.run {
这个run没啥用，也可以去掉

2024-07-05 03:51 UTC, mingshewhe approved these changes

2024-07-05 03:53 UTC, irwinsun commented on support-files/sql/1001_ci_process_ddl_mysql.sql
> +    `ASYNC_STATUS` varchar(32) COMMENT '插件异步执行状态',
default  没指定

2024-07-05 03:54 UTC, irwinsun commented on support-files/sql/1001_ci_archive_process_ddl_mysql.sql
> +    `ASYNC_STATUS` varchar(32) COMMENT '插件异步执行状态',
DEFAULT NULL

2024-07-08 06:41 UTC, merged