feat：支持流水线指标监控 #9860
TencentBlueKing/bk-ci pull request #10591
Opened 2024-06-28 08:51 UTC by yongyiduan

2024-07-01 10:18 UTC, irwinsun commented on support-files/sql/2002_v1.x/2010_ci_process-update_v1.10_mysql.sql
> +
这个文件不对，目前 是3.0版本，应该在2004_v3.x

2024-07-03 01:42 UTC, irwinsun commented on src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
> +    fun hdelete(key: String, hashKeys: Array<String>, isDistinguishCluster: Boolean? = false) {
此修改Array的优势是什么

2024-07-03 01:47 UTC, irwinsun commented on src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsHeartBeatService.kt
> +            val heartBeats = redisOperation.hentries(heartBeatKey()) ?: return
这个hash结构数据量会有大多？

2024-07-03 01:47 UTC, irwinsun commented on src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsHeartBeatService.kt
> +            val updateKey = redisOperation.hkeys(MetricsCacheService.updateKey())?.ifEmpty { null } ?: return
这个hash结构key的数量有多少，有没有上限。 担心会爆破

2024-07-03 01:48 UTC, irwinsun commented on src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsHeartBeatService.kt
> +            val losePodKeys = redisOperation.hkeys(MetricsCacheService.podKey(losePod))?.ifEmpty { null } ?: return true
同上，考虑上限爆破

2024-07-03 01:54 UTC, irwinsun commented on src/backend/ci/core/process/biz-engine/src/main/kotlin/com/tencent/devops/process/engine/atom/TaskAtomService.kt
> +            dispatchBroadCastEvent(task, ActionType.START)
构建机启停事件也要广播

2024-07-03 02:02 UTC, irwinsun commented on src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsUserService.kt
> +    private val local = MapMaker()
Map可能在SLEEP清理间隔内，会不会存在无限扩大导致OOM的风险

2024-07-03 03:02 UTC, yongyiduan commented on src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/config/MetricsUserConfig.kt
> +    @Value("\${metrics.user.bkBizId:9}")
已去掉

2024-07-03 03:04 UTC, yongyiduan commented on src/backend/ci/core/common/common-redis/src/main/kotlin/com/tencent/devops/common/redis/RedisOperation.kt
> +    fun hdelete(key: String, hashKeys: Array<String>, isDistinguishCluster: Boolean? = false) {
这个方法原先的实现是有问题的，也没人用，所以没发现

2024-07-03 03:23 UTC, yongyiduan commented on src/backend/ci/core/metrics/biz-metrics/src/main/kotlin/com/tencent/devops/metrics/service/builds/MetricsHeartBeatService.kt
> +            val heartBeats = redisOperation.hentries(heartBeatKey()) ?: return
这个hash的集合数量=metrics服务pod数量，数量基本可控

2024-07-04 02:57 UTC, irwinsun requested changes
根据配置来初始化 bean，对于不需要该功能的就不加载初始化

2024-07-08 06:41 UTC, merged