feat：保存流水线时，校验是否有子流水线循环依赖 #10479
TencentBlueKing/bk-ci pull request #10794
Opened 2024-08-12 08:17 UTC by hejieehe

#10479

2024-08-12 08:17 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-ci?pullRequest=10794) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-ci?pullRequest=10794) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: hejieehe<br/>:x: landun<br/><hr/>**landun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-ci?pullRequest=10794) it.</sub>

2024-10-11 08:43 UTC, mingshewhe requested changes

2024-10-11 08:43 UTC, mingshewhe commented on support-files/sql/1001_ci_process_ddl_mysql.sql
> +  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
ID可以不要

2024-10-11 08:43 UTC, mingshewhe commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/SubPipelineStartUpService.kt
> +        val subPipelineRef = SubPipelineRef(
执行时校验先保留老逻辑，等子流水线关系表数据刷新后再上线

2024-10-11 08:43 UTC, mingshewhe commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/engine/listener/pipeline/MQPipelineCreateListener.kt
> +        watcher.safeAround("updateSubPipelineRef") {
保存关联关系使用同步，不要使用异步

2024-10-11 08:43 UTC, mingshewhe commented on support-files/sql/1001_ci_process_ddl_mysql.sql
> +  `TASK_NAME` varchar(256) DEFAULT NULL COMMENT 'TASK名称',
需要增加插件项目ID，流水线类型，流水线名称，流水线ID字段

2024-11-22 08:52 UTC, mingshewhe requested changes

2024-12-03 09:41 UTC, mingshewhe requested changes

2024-12-03 09:41 UTC, mingshewhe commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> +                subPipelineRefDao.batchAdd(
直接在subPipelineTaskService定义一个batchSave方法，然后传入modelTask进去，不要在外面调用转换

2024-12-03 09:41 UTC, mingshewhe commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRepositoryService.kt
> +                        watcher.start("updateSubPipelineRef")
这里也不要直接全部删除，如果删除和执行刚好同时发生，那么执行时校验会有问题。而且删除已经在model检测那里删了

2024-12-09 10:02 UTC, mingshewhe approved these changes

2025-01-02 08:55 UTC, mingshewhe approved these changes

2025-01-02 08:55 UTC, mingshewhe commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/SubPipelineUpgradeService.kt
> +        logger.info("analysis sub pipeline ref|$subPipelineRefList")
不要把这个对象都输出出来

2025-01-02 08:55 UTC, mingshewhe commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/pipeline/SubPipelineUpgradeService.kt
> +                logger.info("Start to create sub pipeline ref")
可以加上项目ID和流水线ID

2025-02-11 04:08 UTC, irwinsun approved these changes
OK， 多验证可能存在的变量场景

2025-02-12 07:36 UTC, merged