feat：流水线构建详情页重构需求 #7983
TencentBlueKing/bk-ci pull request #8233
Opened 2023-01-06 07:28 UTC by carlyin0801

feat：流水线构建详情页重构需求 #7983
#7983

2023-02-10 02:53 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-ci?pullRequest=8233) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-ci?pullRequest=8233) before we can accept your contribution.<br/>**0** out of **3** committers have signed the CLA.<br/><br/>:x: royalhuang<br/>:x: yongyiduan<br/>:x: carlyin0801<br/><hr/>**royalhuang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-ci?pullRequest=8233) it.</sub>

2023-02-28 09:15 UTC, carlyin0801 commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/BuildTimeCostUtils.kt
> +        right: List<BuildRecordTimeLine.Moment>
差集直接用结合的特性计算更简单易懂，1、left.subtract(right)、right.subtract(left) 2、把第一步的二个结果集合相加就行

2023-02-28 09:15 UTC, carlyin0801 commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/engine/common/BuildTimeCostUtils.kt
> +        val ans: MutableList<BuildRecordTimeLine.Moment> = mutableListOf()
直接left.intersect(right)就可以计算出来

2023-02-28 13:48 UTC, carlyin0801 commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
> +            stage.resetBuildOption()
新的详情页查询逻辑不需要执行这段逻辑吧，可以考虑加个判断

2023-03-01 08:08 UTC, irwinsun commented on src/backend/ci/core/common/common-pipeline/src/main/kotlin/com/tencent/devops/common/pipeline/container/Stage.kt
> +    var executeCount: Int? = 1,
executeCount 这个建议默认为空，如果有值，会持久到编排存储RESOURCE中。
该字段与Container/Element都一样，属于构建运行中产生的，

2023-03-01 08:17 UTC, royalhuang commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
> +        buildContainers: MutableList<Pair<PipelineBuildContainer, Container>>,
这里一开始把name拆出来，发现后续要不断加内容，所以索性传了Container，后续需要增加进var的可以直接加map

2023-03-01 08:20 UTC, royalhuang commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineRuntimeService.kt
> +                    stageId = "", containerId = "",
这个数据用于度量，加上jobId用法本来属于错误，后面容易误导度量

2023-03-01 09:30 UTC, irwinsun commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/PipelineContainerService.kt
>      private val containerBuildDetailService: ContainerBuildDetailService,
无用就删除

2023-03-01 11:33 UTC, irwinsun commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
> +    const val ERROR_PIPELINE_CAN_NOT_DELETE_WHEN_HAVE_BUILD_RECORD = "2101083" // 流水线版本还存在构建记录，不允许删除
补充 SQL

2023-03-02 02:28 UTC, irwinsun commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildDao.kt
> +            if (executeCount == 1) {
这类executeCount逻辑不要放到DAO里，在外面判断，
然后这里只要判断
if ( startTime != null) 就赋值

2023-03-02 02:46 UTC, royalhuang commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/service/record/PipelineBuildRecordService.kt
> +            stage.resetBuildOption()
需要保留，暂时需要把detail那边的计时字段填充一下，否则度量和旧页面上计时数据都为空了

2023-03-02 03:44 UTC, irwinsun commented on src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/lock/PipelineVersionLock.kt
> +class PipelineVersionLock(redisOperation: RedisOperation, pipelineId: String, version: Int) :
misc服务启动时会指定 redisName, 而RedisLock的 set方法会读取这个redisName 拼成真正的LockKey
会导致与process服务Lock出现不一致。 比如灰度与生产

2023-03-02 03:49 UTC, irwinsun commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/engine/dao/PipelineBuildTaskDao.kt
> +    fun getByContainerId(
getByContainerId 这个方法与listByStatus雷同。 建议全并了

2023-03-02 08:49 UTC, royalhuang commented on src/backend/ci/core/process/biz-base/src/main/kotlin/com/tencent/devops/process/dao/BuildDetailDao.kt
> +        with(TPipelineBuildDetail.T_PIPELINE_BUILD_DETAIL) {
已调整

2023-03-02 08:49 UTC, royalhuang commented on src/backend/ci/core/process/api-process/src/main/kotlin/com/tencent/devops/process/constant/ProcessMessageCode.kt
> +    const val ERROR_PIPELINE_CAN_NOT_DELETE_WHEN_HAVE_BUILD_RECORD = "2101083" // 流水线版本还存在构建记录，不允许删除
已补充

2023-03-03 01:25 UTC, irwinsun commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> +            defaultMessage = "构建任务${buildId}不存在",
这里面的信息只有取不到i18n才会用的默认值，所以倒不是啥问题，主要是errorCode对应的i18n配置存在就可以。

2023-03-03 01:25 UTC, irwinsun commented on src/backend/ci/core/process/biz-process/src/main/kotlin/com/tencent/devops/process/service/builds/PipelineBuildFacadeService.kt
> +            defaultMessage = "构建任务${buildId}不存在",
> 要支持国际化，以后新加的代码不要写死中文，给开发人员看的用英文，展示给用户看的以用户设置的语言信息为准

这里面的信息只有取不到i18n才会用的默认值，所以倒不是啥问题，主要是errorCode对应的i18n配置存在就可以。

2023-03-03 01:41 UTC, irwinsun commented on src/backend/ci/core/misc/biz-misc/src/main/kotlin/com/tencent/devops/misc/lock/PipelineVersionLock.kt
> +class PipelineVersionLock(redisOperation: RedisOperation, pipelineId: String, version: Int) :
decorateKey

2023-03-03 01:48 UTC, irwinsun requested changes
继续优化

2023-03-07 07:01 UTC, irwinsun approved these changes

2023-03-13 12:02 UTC, merged