pref:完善部分build类接口权限校验 #8256
TencentBlueKing/bk-ci pull request #8376
Opened 2023-02-17 06:30 UTC by yjieliang

2023-02-27 13:09 UTC, irwinsun requested changes
注意TRIGGER与START_USER的区别，明确后再合并

2023-02-28 06:47 UTC, yjieliang commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/service/ServiceBuildApiPermissionResource.kt
> +    fun getTriggerUser(
已调整

2023-02-28 06:47 UTC, yjieliang commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/aop/BuildApiAspect.kt
> +            if (checkPipelinePermissionResult == true) {
已调整

2023-02-28 14:14 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/annotation/BuildApiPermission.kt
> +    val values: Array<String>
业务类型一般每种对应的处理逻辑都不一样，不要定义成一个数组

2023-02-28 14:14 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/aop/BuildApiAspect.kt
> +                "auth" -> {
逻辑不要写死，可以利用策略等设计模式把逻辑写得可扩展一点

2023-03-06 02:26 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/service/impl/BuildApiHandleAuthServiceImpl.kt
> +                logger.info("verify that user [$buildStartUser] has permission to access information " +
日志打印错了吧，应该是没权限吧

2023-03-06 02:26 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/service/impl/BuildApiHandleAuthServiceImpl.kt
> +            logger.info("ParamName[$it]")
这调试日志不要打印出来，有些接口参数可能很多

2023-03-06 02:26 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/service/impl/BuildApiHandleAuthServiceImpl.kt
> +            logger.info("ParamValue[$it]")
这调试日志不要打印出来，有些接口参数可能很多

2023-03-06 02:26 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/factory/BuildApiHandleFactory.kt
> +                    buildApiHandleMapService = BuildApiHandleAuthServiceImpl(getClient())
client对象在实列化类的时候再获取，因为只会生产一个service类，如果缓存中有service类就无需再定义一个client对象

2023-03-06 02:26 UTC, carlyin0801 commented on src/backend/ci/core/common/common-web/src/main/kotlin/com/tencent/devops/common/web/constant/BuildApiHandleType.kt
> +    UNAUTHORIZED
感觉换成授权校验的英文单词好理解一点

2023-03-07 08:10 UTC, carlyin0801 approved these changes
ok

2023-03-20 08:16 UTC, irwinsun approved these changes

2023-03-20 08:17 UTC, merged