feat: 将 push 事件的运行结果上报至代码库 Tencent#7901
TencentBlueKing/bk-ci pull request #8475
Opened 2023-03-10 00:50 UTC by hejieehe

#7901

2023-03-22 08:02 UTC, mingshewhe approved these changes

2023-03-23 07:14 UTC, irwinsun commented on src/backend/ci/core/common/common-scm/src/main/kotlin/com/tencent/devops/scm/IScm.kt
> +        targetBranch: List<String>? = mutableListOf()
建议没必要new一个允许为空的又是不可变的对象

2023-03-23 07:16 UTC, irwinsun commented on src/backend/ci/core/plugin/biz-plugin/src/main/kotlin/com/tencent/devops/plugin/service/git/CodeWebhookService.kt
> +                                        "~NONE"
这个是MagicNumber之类的吗

2023-03-31 03:38 UTC, irwinsun requested changes
请重新同步代码，并按SQL按新目录规范存放

2023-04-04 03:51 UTC, mingshewhe approved these changes

2023-04-04 04:00 UTC, irwinsun approved these changes

2023-04-06 09:45 UTC, merged