第三方构建机容器化环境支持登录调试 #8915
TencentBlueKing/bk-ci pull request #9045
Opened 2023-06-29 08:16 UTC by tangruotian

2023-07-04 01:40 UTC, irwinsun requested changes

2023-07-04 01:48 UTC, irwinsun commented on src/backend/ci/core/dispatch/biz-dispatch/src/main/kotlin/com/tencent/devops/dispatch/service/ThirdPartyAgentService.kt
> +        while (true) {
1、建议增加超时退出机制
2、增加防重复操作

2023-07-05 02:04 UTC, irwinsun approved these changes

2023-07-05 02:36 UTC, tangruotian reviewed
reviewed

2023-07-07 08:35 UTC, tangruotian reviewed
reviewed logs change

2023-07-11 06:42 UTC, merged